# Generated by Django 5.1.7 on 2025-06-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateCertificate', '0001_initial'),
        ('manageTemplate', '0005_alter_certificatetemplate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageTemplate.certificatetemplate'),
        ),
    ]
