# Generated by Django 5.1.7 on 2025-06-15 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateCertificate', '0003_certificate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
