# Generated by Django 5.2.4 on 2025-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateCertificate', '0004_alter_certificate_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
