# Generated by Django 5.2.4 on 2025-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_candidate_course_title_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='No', max_length=1),
            preserve_default=False,
        ),
    ]
