# Generated by Django 5.2.4 on 2025-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='domain',
        ),
        migrations.AddField(
            model_name='candidate',
            name='project_title',
            field=models.TextField(default='para'),
            preserve_default=False,
        ),
    ]
