# Generated by Django 5.2.4 on 2025-08-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_candidate_domain_candidate_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
    ]
