# Generated by Django 5.1.7 on 2025-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_companysubscription_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
