# Generated by Django 5.1.7 on 2025-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_companysubscription_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='next_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
