# Generated by Django 5.1.7 on 2025-05-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_companysubscription_next_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
