# Generated by Django 5.1.7 on 2025-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_companysubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='validity_period',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
