# Generated by Django 5.1.7 on 2025-06-12 09:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='field_config',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='template_file',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('font', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Helvetica', 'Helvetica'), ('Courier New', 'Courier New')], default='Arial', max_length=50)),
                ('font_size', models.PositiveIntegerField(default=12)),
                ('position_x', models.PositiveIntegerField()),
                ('position_y', models.PositiveIntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='manageTemplate.certificatetemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
