# Generated by Django 5.1.7 on 2025-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0002_alter_certificatetemplate_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
