# Generated by Django 5.1.7 on 2025-06-12 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0003_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
