# Generated by Django 5.1.7 on 2025-06-12 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0004_alter_certificatetemplate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
