# Generated by Django 5.1.7 on 2025-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0005_alter_certificatetemplate_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='font',
            field=models.CharField(choices=[('Times New Roman', 'Times New Roman'), ('Helvetica', 'Helvetica'), ('Courier New', 'Courier New')], default='Helvetica', max_length=50),
        ),
    ]
