# Generated by Django 5.2.4 on 2025-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0006_delete_template_certificatetemplate_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='font',
            field=models.CharField(choices=[('Times-Roman', 'Times New Roman'), ('Helvetica', 'Helvetica'), ('Courier', 'Courier New')], default='Helvetica', max_length=50),
        ),
    ]
