# Generated by Django 5.2.4 on 2025-08-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0007_alter_dynamicfield_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='dynamicfield',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='dynamicfield',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='dynamicfield',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='dynamicfield',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='dynamicfield',
            name='template',
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='font',
            field=models.CharField(default='Helvetica', max_length=50),
        ),
    ]
