# Generated by Django 5.2.4 on 2025-08-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0008_remove_certificatetemplate_preview_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicField',
        ),
    ]
