# Generated by Django 5.2.4 on 2025-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0009_delete_dynamicfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='certificate_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('intermediate_letter', 'Intermediate Letter'), ('completion_certificate', 'Completion Certificate'), ('social_media', 'Social Media')], default='offer_letter', max_length=50),
        ),
    ]
