# Generated by Django 5.2.4 on 2025-08-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTemplate', '0010_certificatetemplate_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
